services:
  app:
    image: php:8.1-fpm
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
    working_dir: /var/www/html
    command: ["php-fpm"]
    entrypoint: |
      bash -c "docker-php-ext-install pdo pdo_mysql && php-fpm"

  web:
    image: nginx
    container_name: laravel_web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ampli
      MYSQL_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
